name: Manual YTM Fix

on:
  workflow_dispatch:

jobs:
  remove-item:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute Raw API Call
        env:
          YTM_OAUTH_JSON: ${{ secrets.YTM_OAUTH_JSON }}
        run: bash remove_item.sh
