name: Get REAL Playlist IDs

on:
  workflow_dispatch:

jobs:
  fetch-ids:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Script
        env:
          YTM_CLIENT_ID: ${{ secrets.YTM_CLIENT_ID }}
          YTM_CLIENT_SECRET: ${{ secrets.YTM_CLIENT_SECRET }}
          YTM_OAUTH_JSON: ${{ secrets.YTM_OAUTH_JSON }}
        run: python get_playlist.py
